### ISSUE TITLE
Default template is too loose on package requirements

### ISSUE THREAD

**Issue by chipbell4** [SpringRoll/SpringRollStudio#11]
The default template specifies `"*"` for it's two dependencies. We should probably tighten that down so that newer SpringRoll projects will install properly, or at least predictably

See here: https://github.com/SpringRoll/SpringRollStudio/blob/master/deploy/assets/templates/default/package.json#L5

**Comment by 902seanryan** [comment]
Very old issue clean up.

Hi Chip!
