### ISSUE TITLE
Way to prevent .git from being copied from a project template?

### ISSUE THREAD

**Issue by probityrules** [SpringRoll/SpringRollStudio#2]
I can remove this manually after creating a new project, but was curious whether there is a way to prevent a SpringRoll template's .git folder from being copied along with all the other template files. I tried adding `"remove": [".git"]` to the springroll-template.json, but this just throws an error.

![untitled](https://cloud.githubusercontent.com/assets/1324745/8754494/efaff458-2c91-11e5-808f-265f1fa98690.png)

**Comment by bigtimebuddy** [comment]
Fixed in release 0.2.8

**Comment by probityrules** [comment]
Awesome; thanks!
