### ISSUE TITLE
Springroll studio captions maker does not save to specified .json file.

### ISSUE THREAD

**Issue by beveretthealy** [SpringRoll/SpringRollStudio#3]
When this dialog pops up when trying to close the captions window:
![screen shot 2015-07-17 at 3 02 57 pm](https://cloud.githubusercontent.com/assets/10728754/8757122/f13ffa9a-2c94-11e5-97f1-553eace46f8d.png)

And you click save, the .json file that is specified for the captions does not get overwritten with any new changes. However, using 'save project' in the file menu works as expected.

**Comment by bigtimebuddy** [comment]
Fixed, will be released in 0.2.8.
