### ISSUE TITLE
Get 'Invalid Project' error when opening tasks window on a project. 

### ISSUE THREAD

**Issue by GopherwoodTodd** [SpringRoll/SpringRollStudio#4]
I created a project and was able to open/use the tasks window successfully. After I created a second project and then tried to return to the original project I got an error when opening the tasks window.

The error says "Invalid project, must contain Grunt task '_springroll_usertasks'.

**Comment by bigtimebuddy** [comment]
Todd, could you create steps to reproduce?

**Comment by GopherwoodTodd** [comment]
I will try to capture better repro steps if it happens again. I just created a new project and transferred files over and it seems to be working fine.

**Comment by bigtimebuddy** [comment]
If it happens again, the other idea worth trying is maybe deleting the *node_modules* folder and opening the tasks again to reinstall all the build plugins.

**Comment by GopherwoodTodd** [comment]
Yeah, I tried that but it didn't fix it.
