### ISSUE TITLE
Repeating actions when using Dev Task

### ISSUE THREAD

**Issue by GopherwoodTodd** [SpringRoll/SpringRollStudio#5]
When using the dev task I've noticed that the output shows the same action being repeated multiple times after every save. The number of times the actions are performed increases if I stop the dev task and restart it. So I'm guessing the task isn't actually being killed.

Here's some example output:

Reloading watch config...

Running "watch" task
Waiting...

Reloading watch config...

Running "watch" task
Waiting...

Reloading watch config...

Running "watch" task
Waiting...

Reloading watch config...

Running "watch" task
Waiting...

Reloading watch config...

Running "watch" task
Waiting...
>> File "src\config\entities\p1-faux-right-paddle.json" changed.

Reloading watch config...

Running "watch" task
Waiting...
>> File "src\config\entities\p1-faux-right-paddle.json" changed.

>> File "src\config\entities\p1-faux-right-paddle.json" changed.

>> File "src\config\entities\p1-faux-right-paddle.json" changed.

>> File "src\config\entities\p1-faux-right-paddle.json" changed.

>> File "src\config\entities\p1-faux-right-paddle.json" changed.

Running "newer:concat-json:debug" (newer) task

Running "newer:concat-json:debug" (newer) task

Running "newer:concat-json:debug" (newer) task

Running "newer:concat-json:debug" (newer) task

Running "newer:concat-json:debug" (newer) task

Running "concat-json:debug" (concat-json) task

Running "newer:concat-json:debug" (newer) task

Running "concat-json:debug" (concat-json) task

Running "concat-json:debug" (concat-json) task

Running "concat-json:debug" (concat-json) task

Running "concat-json:debug" (concat-json) task

Running "concat-json:debug" (concat-json) task

File "deploy/assets/config/config.json" created.

Running "newer-postrun:concat-json:debug:1:C:\xampp\htdocs\Gopherwood\dino-pond-sr\node_modules\grunt-springroll\node_modules\grunt-newer.cache" (newer-postrun) task

Done, without errors.

File "deploy/assets/config/config.json" created.

Running "newer-postrun:concat-json:debug:1:C:\xampp\htdocs\Gopherwood\dino-pond-sr\node_modules\grunt-springroll\node_modules\grunt-newer.cache" (newer-postrun) task

Done, without errors.
Completed in 9.228s at Wed Sep 02 2015 12:37:37 GMT-0400 (Eastern Daylight Time) - Waiting...

File "deploy/assets/config/config.json" created.

Running "newer-postrun:concat-json:debug:1:C:\xampp\htdocs\Gopherwood\dino-pond-sr\node_modules\grunt-springroll\node_modules\grunt-newer.cache" (newer-postrun) task

Done, without errors.
Completed in 9.430s at Wed Sep 02 2015 12:37:37 GMT-0400 (Eastern Daylight Time) - Waiting...

Completed in 9.590s at Wed Sep 02 2015 12:37:37 GMT-0400 (Eastern Daylight Time) - Waiting...

File "deploy/assets/config/config.json" created.

Running "newer-postrun:concat-json:debug:1:C:\xampp\htdocs\Gopherwood\dino-pond-sr\node_modules\grunt-springroll\node_modules\grunt-newer.cache" (newer-postrun) task

Done, without errors.
Completed in 9.753s at Wed Sep 02 2015 12:37:38 GMT-0400 (Eastern Daylight Time) - Waiting...

File "deploy/assets/config/config.json" created.

Running "newer-postrun:concat-json:debug:1:C:\xampp\htdocs\Gopherwood\dino-pond-sr\node_modules\grunt-springroll\node_modules\grunt-newer.cache" (newer-postrun) task

Done, without errors.
Completed in 9.836s at Wed Sep 02 2015 12:37:38 GMT-0400 (Eastern Daylight Time) - Waiting...

File "deploy/assets/config/config.json" created.

Running "newer-postrun:concat-json:debug:1:C:\xampp\htdocs\Gopherwood\dino-pond-sr\node_modules\grunt-springroll\node_modules\grunt-newer.cache" (newer-postrun) task

Done, without errors.
Completed in 9.869s at Wed Sep 02 2015 12:37:38 GMT-0400 (Eastern Daylight Time) - Waiting...

**Comment by bigtimebuddy** [comment]
@GopherwoodTodd I agree, it seems like the dev process isn't getting killed properly. Are you using Window or OS X, what version of OS and Studio? I was unable to reproduce in OS X 10.9.5 in Studio 0.2.12.

**Comment by GopherwoodTodd** [comment]
I'm using Windows 8.1 and Studio 0.2.12

**Comment by GopherwoodTodd** [comment]
I think the repeating is caused by a separate error because repeating seems to start after I get a pop-up message saying "TypeError: undefined is not a function".

This error occurs while I am editting/saving files with the dev task running. It's hard to pin down exactly when the error appears because it appears in the background and I only notice it when I go to check the task output window. Generally though there are a couple of the error windows piled up that need to be closed out.

**Comment by bigtimebuddy** [comment]
I was able to reproduce this on Windows 7 as well.

**Comment by GopherwoodTodd** [comment]
Ok. And just to clarify, after I get that pop-up error, if I stop dev and start it again then it's doubling up.

**Comment by 902seanryan** [comment]
Very old issue clean up
