### ISSUE TITLE
Captions Creator doesn't respond to VO config changes

### ISSUE THREAD

**Issue by ericente** [SpringRoll/SpringRollStudio#7]
A list of VO files is generated in .springroll when Captions Creator is initially opened, but that list doesn't get updated if more VO files are added to the project later. A workaround for this is to delete the .springroll file and let it be regenerated when the project is opened again, but the file list would ideally be updated each time the project is opened, and/or when the refresh button is pressed.

**Comment by bigtimebuddy** [comment]
There's an option in the menu **File -> Sync Audio Files**. I think that does what you're describing.
