### ISSUE TITLE
IE9 game not launching for the first time

### ISSUE THREAD

**Issue by chetansind** [SpringRoll/SpringRollStudio#8]
springroll version 0.3
springroll studio: 0.2.12
OS: Windows 7, 
Browser: **IE9**

Game will not launch for the first time, when we refresh the browser again it works.

On first launch it returns with the below error:
**SCRIPT5007: Unable to get value of the property 'content': object is null or undefined libraries.js, Unable to get value of the property 'content': object is null or undefined**

But the game developed in springroll version 0.4, works fine in first launch.

We tried removing the existing components and node modules. Re-installed the task modules

Please suggest.

**Comment by bigtimebuddy** [comment]
About this issue: SoundJS and PreloadJS share common code. There is an abstraction of the URL Request. PreloadJS contains the latest up-to-date bug fixes for IE9 and SoundJS (even on CreateJS’s main repo) contains the outdated common code. The fix, is to re-order the dependencies in **springroll.json** to make sure PreloadJS comes *after* SoundJS and that PreloadJS’s common code overrides the older common code in SoundJS.

```js
"libraries": [
	"components/soundjs/lib/soundjs.min.js",
	"components/preloadjs/lib/preloadjs.min.js",  // preloadjs after soundjs!
	...	
],
"librariesDebug": [
	"components/soundjs/lib/soundjs.min.js",
	"components/preloadjs/lib/preloadjs.combined.js", // preloadjs after soundjs!
	...
],
```
